<?php

namespace MagnetosCompany\MainBundle\Repository;

/**
 * ActivatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivatorRepository extends \Doctrine\ORM\EntityRepository
{
}
