<?php

namespace MagnetosCompany\MainBundle\Repository;

/**
 * SensorValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorValueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByLastId()
    {
        $query = $this->createQueryBuilder('p')
            //->where('p.sensorId =:sensorId')
            ->orderBy('p.id', 'DESC')
            ->setMaxResults(1)
            //->setParameter('sensorId', $sensorId)
            ->getQuery();

        return $query;
    }
}
