<?php

namespace MagnetosCompany\MainBundle\Repository;

/**
 * SensorValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorValueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByLastIdByName($sensorId)
    {
        $query = $this->createQueryBuilder('d')
            ->where('d.sensorId = :sensorId')
            ->orderBy('d.id', 'DESC')
            ->setParameter('sensorId', $sensorId)
            ->setMaxResults(1)
            ->getQuery();

        return $query;
    }

    public function getByLastId()
    {
        $query = $this->createQueryBuilder('d')
            ->orderBy('d.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery();

        return $query;
    }
}
