dispatcher_devices:
    path:     /dispatcher/devices
    defaults: { _controller: DispatcherBundle:Devices:devices }

dispatcher_interfaces:
    path:     /interfaces/1wire
    defaults: { _controller: DispatcherBundle:Devices:interfaces }